name: Check Site

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: 1.2.8

      - name: Build
        run: bun install && bun run build

      - name: Check Quality
        run: |
          bun quality:check
