name: Publish Site

on:
  workflow_dispatch:
  push:
    branches:
      - release

permissions: write-all

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.8

      - name: Build
        run: bun install && bun run build

      - name: Check Quality
        run: |
          bun quality:check

      - name: Upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  release:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - package
    steps:
      - name: Publish
        uses: actions/deploy-pages@v1
