name: Publish Site

on:
  workflow_dispatch:

permissions: write-all

jobs:
  check-and-package:
    name: Check & Package Site
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: 1.2.8

      - name: Build
        run: bun install && bun run build

      - name: Check Quality
        run: |
          bun quality:check

      - name: Upload
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist

  release:
    name: Publish Site
    runs-on: ubuntu-latest
    needs:
      - check-and-package
    steps:
      - name: Publish
        uses: actions/deploy-pages@v4.0.5
